#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source ${OPENSHIFT_REPO_DIR}/.openshift/nave

# Use `nave` to make sure we use the right `node` and `npm` versions.
# We set the `$HOME` environment variable to data dir as this is the only place
# where we can write and `npm` will need to do so in home.
eval $WITH_NAVE npm install bower

echo Validating NodeJs Version:
eval $WITH_NAVE node -v