#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
##### nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

source ${OPENSHIFT_REPO_DIR}/.openshift/.leinrc

cd ${OPENSHIFT_REPO_DIR}
# ${OPENSHIFT_DATA_DIR}/lein pdo sass once, cljsbuild once adv >${OPENSHIFT_LOG_DIR}/build.log 2>&1
nohup ${OPENSHIFT_DATA_DIR}/lein with-profile -dev,-user trampoline run >${OPENSHIFT_LOG_DIR}/server.log 2>&1 &
