#!/bin/bash

source ${OPENSHIFT_REPO_DIR}/.openshift/.leinrc

cd ${OPENSHIFT_REPO_DIR}
echo "Starting Application..."
nohup ${OPENSHIFT_DATA_DIR}/lein with-profile -dev,-user trampoline run >${OPENSHIFT_LOG_DIR}/server.log 2>&1 &
