#!/bin/bash

NAVE_SCRIPT=${OPENSHIFT_DATA_DIR}nave/nave.sh

# If `nave` doesn't exist we get it from GitHub.
if [ ! -f $NAVE_SCRIPT ]; then
  echo 'Downloading isaacs/nave from GitHub...'
  git clone git://github.com/isaacs/nave.git ${OPENSHIFT_DATA_DIR}nave

fi

# We go into the repo where the app lives so we can run `npm install` in there.
cd $OPENSHIFT_REPO_DIR

NODE_VER=6.5.0

NAVE_ENV="TEMP=$OPENSHIFT_TMP_DIR SHELL=/bin/bash HOME=$OPENSHIFT_DATA_DIR"
NAVE="${NAVE_ENV} $NAVE_SCRIPT"
WITH_NAVE="$NAVE use $NODE_VER "
